### PR TITLE
Improved LaVision support

### PR DESCRIPTION
**Pull request by seanwarren**

### CODE REVIEW

**Comment by imunro** [comment]
I like the idea of pulling everything into a parseLaVision file but it seems to have gone missing from this PR ?

**Comment by seanwarren** [comment]
Apologies, seem to have added some random other file instead! Will commit tomorrow am

**Comment by imunro** [comment]
No problem.

**Comment by imunro** [comment]
Looks  good generally - I would really like, however to retain the questdlg bit.
https://github.com/flimfit/FLIMfit/blob/master/FLIMfitFrontEnd/Classes/%40flim_data_series/get_image_dimensions.m#L162-L167
otherwise I think there is a risk of confusion when users open non-FLIM ome-tiffs with FLIMfit & also I think it's a useful reminder to users that problems arise for LaVision's end not ours!

**Comment by imunro** [comment]
I pushed that now. Feel free to revert if you're unhappy. My guess is that checking the schema version is the fastest check we can do. The intention being to minimise the extent to which  this LaVision stuff slows down  loading valid ome-tiffs.

**Comment by imunro** [comment]
Should now be reverted to "tested" changes only and ready to merge. Let's decide on whether to use the "are you sure ?" LaVision prompt late. It's only one line after all.

**Pull request merged**
